/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_llh_com_ffmpegstudy_MainActivity */

#ifndef _Included_ndk_llh_com_ffmpegstudy_MainActivity
#define _Included_ndk_llh_com_ffmpegstudy_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_llh_com_ffmpegstudy_MainActivity
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_llh_com_ffmpegstudy_MainActivity_avformatinfo
  (JNIEnv *, jobject);

/*
 * Class:     ndk_llh_com_ffmpegstudy_MainActivity
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_llh_com_ffmpegstudy_MainActivity_avcodecinfo
  (JNIEnv *, jobject);

/*
 * Class:     ndk_llh_com_ffmpegstudy_MainActivity
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_llh_com_ffmpegstudy_MainActivity_avfilterinfo
  (JNIEnv *, jobject);

/*
 * Class:     ndk_llh_com_ffmpegstudy_MainActivity
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_llh_com_ffmpegstudy_MainActivity_configurationinfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
